import 'package:flutter/material.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup24Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup23Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup26Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup22Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedCantidaddepizzasWidget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generateddetalleswidget1/generated/GeneratedEscojaunabebidaWidget1.dart';

/* Component Detalles
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetallesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 380.0,
        height: 523.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 28.0,
                child: GeneratedEscojaunabebidaWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 198.53958129882812,
                right: null,
                bottom: null,
                width: 162.0,
                height: 65.37499237060547,
                child: GeneratedGroup13Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 65.375,
                child: GeneratedGroup14Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 65.37503051757812,
                child: GeneratedGroup15Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 24.0,
                child: GeneratedGroup22Widget1(),
              ),
              Positioned(
                left: 195.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 159.25,
                height: 42.0,
                child: GeneratedGroup26Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 24.0,
                child: GeneratedGroup24Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 24.0,
                child: GeneratedGroup23Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.09303283691406,
                child: GeneratedGroup25Widget1(),
              ),
              Positioned(
                left: 97.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 42.0,
                child: GeneratedCantidaddepizzasWidget1(),
              )
            ]),
      ),
    ));
  }
}
