import 'package:flutter/material.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedBienvenidodevueltaWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedIngresatusdatosWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedloginwidget/generated/GeneratedUxRhrU8fPHQWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 620.0,
                child: GeneratedUxRhrU8fPHQWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 37.0,
                child: GeneratedBienvenidodevueltaWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 30.0,
                child: GeneratedIngresatusdatosWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 22.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              )
            ]),
      ),
    ));
  }
}
