import 'package:flutter/material.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedPortraitWidget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup42Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedMenusuperiorWidget3.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/lirucisa_iosapp/generatedperfilwidget10/generated/GeneratedGroup40Widget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget3(),
              ),
              Positioned(
                left: 17.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 450.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 100.0,
                child: GeneratedPortraitWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup40Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup45Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedGroup47Widget(),
              )
            ]),
      ),
    ));
  }
}
